PERSTAT/Models/Assignment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PERSTAT.Models
{
    public class Assignment
    {
        [Key]
        [Required]
        public int AssignmentId { get; set; }
       
        [Display(Name ="Person")]
        public int PeopleId { get; set; }

        public People People { get; set; }

      
        [Display(Name ="Mission")]
        public int MissionId { get; set; }
 
        public Missions Mission { get; set; }

        [DataType(DataType.Date)]
        public DateTime DateStart { get; set; }


        [DataType(DataType.Date)]
        [DateGreaterThan("DateStart")]
        public DateTime DateEnd { get; set; }


        [Display(Name = "Incident")]
        public int IncidentId { get; set; } = 1;
        public Incident Incident { get; set; }

        [Display(Name="Location")]
        public int LocationId { get; set; }
        public Locations Location { get; set; }
      
    }
}

PERSTAT/Controllers/AssignmentController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using PERSTAT.Data;
using PERSTAT.Models;

namespace PERSTAT.Controllers
{
    public class AssignmentController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        private readonly IConfiguration _config;

        public AssignmentController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        public SqlConnection Connection
        {
            get
            {
                return new SqlConnection(_config.GetConnectionString("DefaultConnection"));
            }
        }

        // GET: Assignment
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Assignment
                .Include(a => a.People)
                .Include(a => a.People.Status)
                .Include(a => a.People.Organization)
                .Include(a => a.Mission)
                .Include(a => a.Incident)
                .Include(a => a.Location)
                .Where(p => p.DateEnd > (DateTime.Now).AddDays(-1))
                .OrderByDescending(p => p.DateEnd);
            return View(await applicationDbContext.ToListAsync());

        }

        // GET: Assignment/Details/5
        [Authorize]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var assignment = await _context.Assignment
                .Include(a => a.People)
                .Include(a => a.Mission)
                .Include(a => a.Incident)
                .Include(a => a.Location)
                .FirstAsync(a => a.AssignmentId == id);
            if (assignment == null)
            {
                return NotFound();
            }
            return View(assignment);
        }
        public async Task<IActionResult> GetPeopleByMission(int id)
        {
            var groupByM = _context.Assignment
                .Include(p => p.People)
                .Include(p => p.Mission)
                .Include(p => p.Location)
                .Include(p => p.People.Status)
                .Include(p => p.People.Organization)
                .Where(p => p.MissionId == id && p.DateEnd > (DateTime.Now).AddDays(-1))
                .OrderByDescending(p => p.DateEnd);

            var count = groupByM.Count();

            if (groupByM == null)
            {
                return NotFound();
            }
            return View(await groupByM.ToListAsync());
        }
        public async Task<IActionResult> GetPeopleByLocation(int id)
        {
            var groupByM = _context.Assignment
                .Include(p => p.People)
                .Include(p => p.Mission)
                .Include(p => p.Location)
                .Include(p => p.People.Status)
                .Include(p => p.People.Organization)
                .Where(p => p.LocationId == id && p.DateEnd > (DateTime.Now).AddDays(-1))
                .OrderByDescending(p => p.DateEnd);

            var count = groupByM.Count();

            if (groupByM == null)
            {
                return NotFound();
            }
            return View(await groupByM.ToListAsync());
        }

        // GET: Assignment/Create
        [Authorize]
        public IActionResult Create()
        {
            var detailedLocation = _context.Locations
                .Include(l => l.State).Select(s => new
                {
                    LocationId = s.LocationId,
                    LocationString = s.State.StateShort + " " + s.LocationCity + " ( " + s.LocationDetail + ")"
                }).ToList();

            var detailedPerson = _context.People.OrderBy(p => p.NameLast)
                .ThenBy(p => p.NameFirst)
                .Include(p => p.Organization).Select(i => new
                {
                    PeopleId = i.Id,
                    PeopleString = i.NameLast + ", " + i.NameFirst + " ( " + i.Organization.OrganizationName + ")"
                }).ToList();
            var detailedMission = _context.Missions.Select(m => new
            {
                MissionId = m.Id,
                MissionString = m.MissionTitle
            }).ToList();

            var detailedIncident = _context.Incident
                .Include(i => i.IncidentTypeId)
                .Include(t => t.Type)
                .Select(t => new
                {
                    IncidentId = t.Type,
                    IncidentString = t.Type.TypeIncident
                }).ToList();



            ViewData["PeopleId"] = new SelectList(detailedPerson, "PeopleId", "PeopleString");
            ViewData["LocationId"] = new SelectList(detailedLocation, "LocationId", "LocationString");
            ViewData["MissionId"] = new SelectList(detailedMission, "MissionId", "MissionString");
            ViewData["IncidentId"] = new SelectList(detailedIncident, "IncidentId", "IncidentString");
            ViewBag.message = "";
            return View();
        }

        // POST: Assignment/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("PeopleId, MissionId, DateStart, DateEnd, LocationId, IncidentId")]Assignment assignment)
        {

            var detailedLocation = _context.Locations
            .Include(l => l.State).Select(s => new
            {
                LocationId = s.LocationId,
                LocationString = s.State.StateShort + " " + s.LocationCity + " ( " + s.LocationDetail + ")"
            }).ToList();

            var detailedPerson = _context.People
                .Include(p => p.Organization).Select(i => new
                {
                    PeopleId = i.Id,
                    PeopleString = i.NameFirst + " " + i.NameMiddle + " " + i.NameLast + " ( " + i.Organization.OrganizationName + ")"
                }).ToList();
            var detailedMission = _context.Missions.Select(m => new
            {
                MissionId = m.Id,
                MissionString = m.MissionTitle
            }).ToList();

            var detailedIncident = _context.Incident
               .Include(i => i.IncidentTypeId)
               .Include(t => t.Type)
               .Select(t => new
               {
                   IncidentId = t.Type,
                   IncidentString = t.Type.TypeIncident
               }).ToList();

            ViewData["PeopleId"] = new SelectList(detailedPerson, "PeopleId", "PeopleString");
            ViewData["LocationId"] = new SelectList(detailedLocation, "LocationId", "LocationString");
            ViewData["MissionId"] = new SelectList(detailedMission, "MissionId", "MissionString");
            ViewData["IncidentId"] = new SelectList(detailedIncident, "IncidentId", "IncidentString");

            if (ModelState.IsValid)
            {
                _context.Add(assignment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(assignment);


        }


        [Authorize]
        // GET: Assignment/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var assignment = await _context.Assignment.FindAsync(id);
            if (assignment == null)
            {
                return NotFound();
            }
            var detailedLocation = _context.Locations
            .Include(l => l.State).Select(s => new
            {
                LocationId = s.LocationId,
                LocationString = s.State.StateShort + " " + s.LocationCity + " ( " + s.LocationDetail + ")"
            }).ToList();

            var detailedPerson = _context.People
                .Include(p => p.Organization).Select(i => new
                {
                    PeopleId = i.Id,
                    PeopleString = i.NameFirst + " " +  " " + i.NameLast + " ( " + i.Organization.OrganizationName + ")"
                }).ToList();
            var detailedMission = _context.Missions.Select(m => new
            {
                MissionId = m.Id,
                MissionString = m.MissionTitle
            }).ToList();

            var detailedIncident = _context.Incident
               .Include(i => i.Type)
               .Select(t => new
               {
                   IncidentTypeId = t.IncidentTypeId,
                   IncidentString = t.Type
               }).ToList();

            ViewData["PeopleId"] = new SelectList(detailedPerson, "PeopleId", "PeopleString");
            ViewData["LocationId"] = new SelectList(detailedLocation, "LocationId", "LocationString");
            ViewData["MissionId"] = new SelectList(detailedMission, "MissionId", "MissionString");
            ViewData["IncidentId"] = new SelectList(detailedIncident, "IncidentId", "IncidentString");
            return View(assignment);
        }

        // POST: Assignment/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AssignmentId, PeopleId, LocationId, MissionId, DateStart, DateEnd, IncidentId")]Assignment assignment)
        {
            if (id != assignment.AssignmentId)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {

PERSTAT/Views/Assignment/Create.cshtml
@model PERSTAT.Models.Assignment

@{
    ViewData["Title"] = "Create";

}


<h4>Assignment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PeopleId" class="control-label"></label>
                <select asp-for="PeopleId" class="form-control" asp-items="ViewBag.PeopleId"></select>
            </div>
            <div class="form-group">
                <label asp-for="MissionId" class="control-label"></label>
                <select asp-for="MissionId" class="form-control" asp-items="ViewBag.MissionId"></select>
            </div>
            <div class="form-group">
                <label asp-for="DateStart" class="control-label"></label>
                <input asp-for="DateStart" class="form-control" />
                <span asp-validation-for="DateStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateEnd" class="control-label"></label>
                <input asp-for="DateEnd" class="form-control" />
                <span asp-validation-for="DateEnd" class="text-danger"></span>
            </div>
            @*
                
            <div class="form-group">
                <label asp-for="IncidentId" class="control-label"></label>
                <select asp-for="IncidentId" class="form-control" asp-items="ViewBag.IncidentId"></select>
            </div>
            *@

            <div class="form-group">
                <label asp-for="LocationId" class="control-label"></label>
                <select asp-for="LocationId" class="form-control" asp-items="ViewBag.LocationId"></select>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


   
    <div>
        <a asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

PERSTAT/Views/Assignment/Delete.cshtml
@model PERSTAT.Models.Assignment

@{
    ViewData["Title"] = "Delete";
}

<h1>Are you sure you want to delete this?</h1>
<h2>
    <strong>
        If the end date has changed, edit the end date!
    </strong>
</h2>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.People)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.People.NameFirst)
            @Html.DisplayFor(model => model.People.NameLast)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mission)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mission.MissionTitle)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateStart)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateStart)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateEnd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateEnd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class="col-sm-10">
           @Html.DisplayFor(model => model.Location.LocationCity)  
            </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="AssignmentId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PERSTAT/Views/Assignment/Details.cshtml
@model PERSTAT.Models.Assignment

@{
    ViewData["Title"] = "Details";
}


<div>
    <h4>Assignment</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Mission)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Mission.MissionTitle)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateStart)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateStart)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateEnd)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateEnd)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Location.LocationCity),
            @Html.DisplayFor(model => model.Location.LocationDetail)
        </dd>
    </dl>
</div>


    <div>
        <a asp-action="Index">Back to List</a>
    </div>

PERSTAT/Views/Assignment/Edit.cshtml
@model PERSTAT.Models.Assignment

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Assignment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AssignmentId" />
            <div class="form-group">
                <label asp-for="PeopleId" class="control-label"></label>
                <select asp-for="PeopleId" class="form-control" asp-items="ViewBag.PeopleId"></select>
                <span asp-validation-for="PeopleId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MissionId" class="control-label"></label>
                <select asp-for="MissionId" class="form-control" asp-items="ViewBag.MissionId"></select>
                <span asp-validation-for="MissionId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateStart" class="control-label"></label>
                <input asp-for="DateStart" class="form-control" />
                <span asp-validation-for="DateStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateEnd" class="control-label"></label>
                <input asp-for="DateEnd" class="form-control" />
                <span asp-validation-for="DateEnd" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="LocationId" class="control-label"></label>
                <select asp-for="LocationId" class="form-control" asp-items="ViewBag.LocationId"></select>
                <span asp-validation-for="LocationId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PERSTAT/Views/Assignment/GetAssignmentsByPerson.cshtml
@model IEnumerable<PERSTAT.Models.Assignment>

@{
    ViewData["Title"] = "GetAssignmentsByPerson";
}

<h1>All Assignments for This Person</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                Who
            </th>
            <th>
                Mission
            </th>
            <th>
                Location
            </th>
            <th>
                Start Date
            </th>
            <th>
                End Date
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.People.NameFirst)
                    @Html.DisplayFor(modelItem => item.People.NameLast)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Mission.MissionTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Location.LocationCity), @Html.DisplayFor(modelItem => item.Location.State.StateShort)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateStart)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateEnd)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.AssignmentId">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.AssignmentId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.AssignmentId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

PERSTAT/Views/Assignment/GetAssignmentsByStatus.cshtml
@model IEnumerable<PERSTAT.Models.Assignment>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
@{
    ViewData["Title"] = "GetAssignmentsByStatus";
}

<h1>All Assignments in this status</h1>

<p>

</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.People)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mission)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                Status
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateStart)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateEnd)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.People.NameFirst)
                    @Html.DisplayFor(modelItem => item.People.NameLast)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Mission.MissionTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Location.LocationCity), @Html.DisplayFor(modelItem => item.Location.State.StateShort)
                </td>
                <td>
                    <strong>
                        @Html.DisplayFor(modelItem => item.People.Status.StatusName)
                    </strong>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateStart)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateEnd)
                </td>
                <td>

                    <a asp-action="Details" asp-route-id="@item.AssignmentId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.AssignmentId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

PERSTAT/Views/Assignment/GetPeopleByLocation.cshtml
@model IEnumerable<PERSTAT.Models.Assignment>

@{
    ViewData["Title"] = "GetPeopleByLocation";
}

<h1>Everyone at This Location</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.People)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mission)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateStart)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateEnd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Incident)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.People.Title)
                @Html.DisplayFor(modelItem => item.People.NameFirst)
                @Html.DisplayFor(modelItem => item.People.NameLast)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mission.MissionTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateStart)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateEnd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location.LocationCity)
                @Html.DisplayFor(modelItem => item.Location.LocationDetail)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.AssignmentId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.AssignmentId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.AssignmentId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

PERSTAT/Views/Assignment/GetPeopleByMission.cshtml
@model IEnumerable<PERSTAT.Models.Assignment>

@{
    ViewData["Title"] = "GetPeopleByMission";
}

<h1>Mission Support</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.People)
            </th>
            <th>
                Status
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mission)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateStart)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateEnd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.People.NameFirst)
                @Html.DisplayFor(modelItem => item.People.NameLast)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.People.Status.StatusName)
            </td>
            <td><strong>
                @Html.DisplayFor(modelItem => item.Mission.MissionTitle)
                </strong>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateStart)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateEnd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location.State)
                @Html.DisplayFor(modelItem => item.Location.LocationCity)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.AssignmentId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.AssignmentId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

PERSTAT/Views/Assignment/Index.cshtml
@model IEnumerable<PERSTAT.Models.Assignment>

@{
    ViewData["Title"] = "Index";
}

<h1>All Current Assignments</h1>

<p>
    <a asp-action="Create" asp-controller="Assignment" >Add an assignment</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.People)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.People.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mission)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateStart)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateEnd)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a asp-action="GetAssignmentsByPerson" asp-controller="Assignment" asp-route-id="@item.PeopleId">
                    @Html.DisplayFor(modelItem => item.People.NameFirst)
                    @Html.DisplayFor(modelItem => item.People.NameLast)
                </a>
            </td>
            <th>
                <a asp-action="GetAssignmentsByStatus" asp-controller="Assignment" asp-route-id="@item.People.StatusId">
                    @Html.DisplayFor(model => item.People.Status.StatusName)
                </a>
            </th>

            <td>
                <a asp-action="GetPeopleByMission" asp-controller="Assignment" asp-route-id="@item.MissionId">
                    @Html.DisplayFor(modelItem => item.Mission.MissionTitle)
                </a>
            </td>
            <td>
                <a asp-action="GetPeopleByLocation" asp-controller="Assignment" asp-route-id="@item.LocationId">
                    @Html.DisplayFor(modelItem => item.Location.LocationCity),
                    @Html.DisplayFor(modelItem => item.Location.LocationDetail)
                    </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateStart)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateEnd)
            </td>
            <td>
            <a asp-action="Delete" asp-route-id="@item.AssignmentId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

PERSTAT/Views/Assignment/errorv.cshtml
@model PERSTAT.Models.Assignment

@{
    ViewData["Title"] = "View";
}

<h1>End date must be after the start date!</h1>

<hr />
<div class="row">
    <div class="col-md-4">
     
            
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}