PERSTAT/Models/Locations.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PERSTAT.Models
{
    public class Locations
    {
        [Key]
        [Required]
        public int LocationId { get; set; }

        public string LocationCity { get; set; }

        public string LocationDetail { get; set; }

        public int StateId { get; set; }
        public States State { get; set; }

        public int CountyId { get; set; }
        public Counties County { get; set; }

        public ICollection<Missions> Missions { get; set; }


        public ICollection<Assignment> Assignments { get; set; }
    }
}

PERSTAT/Controllers/CountiesController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using PERSTAT.Data;
using PERSTAT.Models;

namespace PERSTAT.Controllers
{
    public class CountiesController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IConfiguration _config;

        public CountiesController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;

        }

        public SqlConnection Connection
        {
            get
            {
                return new SqlConnection(_config.GetConnectionString("DefaultConnection"));
            }
        }


        // GET: Counties
        [Authorize]
        public async Task<ActionResult> Index()
        {
            var applicationDbContext = _context.Counties
                .Include(c => c.State)
                .OrderBy(c => c.State)
                .ThenBy(c => c.CountyName);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Counties/Details/5
        public ActionResult Details(int id)
        {
            ViewData["StateId"] = new SelectList(_context.States, "StateId", "StateName");
            return View();
        }

        [Authorize]
        // GET: Counties/Create
        public IActionResult Create()
        {
            ViewData["StateId"] = new SelectList(_context.States, "StateId", "StateName");
            return View();
        }

        // POST: Counties/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("Id, CountyName, StateId")] Counties county)
        {
            if (ModelState.IsValid)
            {
                _context.Add(county);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["StateId"] = new SelectList(_context.States, "StateId", "StateName");
            return View(county);

        }


        // GET: Counties/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var county= await _context.Counties
                .FindAsync(id);

            if (county== null)
            {
                return NotFound();
            }
            ViewData["StateId"] = new SelectList(_context.States, "StateId", "StateName");
            return View(county);
        }

        // POST: Counties/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(int id, [Bind("Id, CountyName, StateId")]Counties county)
        {
            if (id != county.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(county);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CountyExists(county.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["StateId"] = new SelectList(_context.States, "StateId", "StateName");
            return View(county);
        }

        [Authorize]
        // GET: Counties/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var county = await _context.Counties
                .Include(c => c.State)
                .FirstOrDefaultAsync(c => c.Id== id);
            if (county == null)
            {
                return NotFound();
            }
            return View(county);
        }

        // POST: Counties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var county = await _context.Counties.FindAsync(id);
                _context.Counties.Remove(county);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ViewBag.Message = "You must remove related locations before you can remove county";
                return View();
            }
        }
        private bool CountyExists(int id)
        {
            return _context.Counties.Any(e => e.Id == id);
        }
    }
}

PERSTAT/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using PERSTAT.Data;
using PERSTAT.Models;

namespace PERSTAT.Controllers
{
    public class LocationsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        private readonly IConfiguration _config;

        public LocationsController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        public SqlConnection Connection
        {
            get
            {
                return new SqlConnection(_config.GetConnectionString("DefaultConnection"));
            }
        }


        // GET: Locations
        [Authorize]
        public async Task<ActionResult> Index()

        {
            var applicationDbContext = _context.Locations.OrderBy(l => l.State.StateShort).ThenBy(l => l.LocationCity)
                .Include(p => p.State)
                .Include(p => p.County)
                .OrderBy(l => l.State.StateShort)
                .ThenBy(l => l.County.CountyName)
                .ThenBy(l => l.LocationCity);
            return View(await applicationDbContext.ToListAsync());
        }
        [Authorize]
        // GET: Locations/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Locations/Create
        public ActionResult Create()
        {

            ViewData["StateId"] = new SelectList(_context.States, "StateId", "StateName");

            var betterCounty = _context.Counties.OrderBy(c => c.CountyName);
            ViewData["CountyId"] = new SelectList(betterCounty, "Id", "CountyName");
            return View();
        }
        [Authorize]
        // POST: Locations/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("LocationCity, LocationDetail, CountyId, StateId")]Locations location)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(location);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                ViewData["StateId"] = new SelectList(_context.States, "StateId", "StateName");
                var betterCounty = _context.Counties.OrderBy(c => c.CountyName);
                ViewData["CountyId"] = new SelectList(betterCounty, "Id", "CountyName");

                return View(location);
            }
            catch
            {
                return View();
            }
        }

        [Authorize]
        // GET: Locations/Edit
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var location = await _context.Locations.FindAsync(id);
            if (location == null)
            {
                return NotFound();
            }
            ViewData["StateId"] = new SelectList(_context.States, "StateId", "StateName");

            var betterCounty = _context.Counties.OrderBy(c => c.CountyName);
            ViewData["CountyId"] = new SelectList(betterCounty, "Id", "CountyName");

            return View(location);
        }

        // POST: Locations/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LocationId, LocationCity, LocationDetail, StateId, CountyId ")]Locations location)
        {
            if (id != location.LocationId)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(location);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LocationExists(location.LocationId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["StateId"] = new SelectList(_context.States, "StateId", "StateName");
            ViewData["CountyId"] = new SelectList(_context.Counties, "Id", "CountyName");
            return View(location);
        }

            public string Message = "";

        // GET: Locations/Delete/5
        [Authorize]
        public async Task<ActionResult> Delete(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }
            var location = await _context.Locations
                .Include(p => p.State)
                .Include(p => p.County)
                .FirstOrDefaultAsync(l => l.LocationId == id);
            if (location == null)
            {
                return NotFound();
            }
            return View(location);
        }
        

        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var location = await _context.Locations.FindAsync(id);
                _context.Locations.Remove(location);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ViewBag.Message = "Cannot remove while related assignments exist.";
                return View();
            }
        }
                


        private bool LocationExists(int id)
        {
            return _context.Locations.Any(e => e.LocationId == id);
        }
    }
}

PERSTAT/Views/Locations/Create.cshtml
@model PERSTAT.Models.Locations

@{
    ViewData["Title"] = "Create";
}


<h4>New Location</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LocationCity" class="control-label"></label>
                <input asp-for="LocationCity" class="form-control" />
                <span asp-validation-for="LocationCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationDetail" class="control-label"></label>
                <input asp-for="LocationDetail" class="form-control" />
                <span asp-validation-for="LocationDetail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StateId" class="control-label"></label>
                <select asp-for="StateId" class ="form-control" asp-items="ViewBag.StateId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CountyId" class="control-label"></label>
                <select asp-for="CountyId" class ="form-control" asp-items="ViewBag.CountyId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PERSTAT/Views/Locations/Delete.cshtml
@model PERSTAT.Models.Locations

@{
    ViewData["Title"] = "Delete";
}

<h3>Are you sure you want to delete this location?</h3>
<div>
    <hr />

    <dl class="row">

        <dd class="col-sm-2">
            @Html.DisplayNameFor(model => model.LocationCity)
        </dd>
        <dt class="col-sm-10">
            @Html.DisplayFor(model => model.LocationCity)
        </dt>
        <dd class="col-sm-2">
            @Html.DisplayNameFor(model => model.LocationDetail)
        </dd>
        <dt class="col-sm-10">
            @Html.DisplayFor(model => model.LocationDetail)
        </dt>
        <dd class="col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dd>
        <dt class="col-sm-10">
            @Html.DisplayFor(model => model.State.StateName)
        </dt>
        <dd class="col-sm-2">
            @Html.DisplayNameFor(model => model.County)
        </dd>
        <dt class="col-sm-10">
            @Html.DisplayFor(model => model.County.CountyName)
        </dt>
    </dl>
    <h1>@ViewBag.Message</h1>
    <form asp-action="Delete">
        <input type="hidden" asp-for="LocationId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PERSTAT/Views/Locations/Edit.cshtml
@model PERSTAT.Models.Locations

@{
    ViewData["Title"] = "Edit";
}


<h4>Edit Location</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="LocationId" />
            <div class="form-group">
                <label asp-for="LocationCity" class="control-label"></label>
                <input asp-for="LocationCity" class="form-control" />
                <span asp-validation-for="LocationCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationDetail" class="control-label"></label>
                <input asp-for="LocationDetail" class="form-control" />
                <span asp-validation-for="LocationDetail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StateId" class="control-label"></label>
                <select asp-for="StateId" class="form-control" asp-items="ViewBag.StateId"></select>
                <span asp-validation-for="StateId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CountyId" class="control-label"></label>
                <select asp-for="CountyId" class="form-control" asp-items="ViewBag.CountyId"></select>
                <span asp-validation-for="CountyId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PERSTAT/Views/Locations/Index.cshtml
@model IEnumerable<PERSTAT.Models.Locations>

@{
    ViewData["Title"] = "Index";
}

<h1>Locations</h1>

<p>
    <a asp-action="Create">Add a New Location</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LocationCity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LocationDetail)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.County)
            </th>
            <th>
                <a asp-action="Index" asp-controller="Counties">Manage Counties</a>
            </th>

        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.State.StateShort)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LocationCity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LocationDetail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.County.CountyName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.LocationId">Edit</a>
                ||
                <a asp-action="Delete" asp-route-id="@item.LocationId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>